<a href="https://colab.research.google.com/github/gajalgarg09/Predictive-Analysis/blob/main/Predictive_Lab_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load a CSV file into a DataFrame
df_csv = pd.read_csv('/content/data1.csv')

In [ ]:
df_csv

   S. NO             Name  SAP ID  Subject 1 Subject 2 Subject 3
0       1      Gazal Garg    9972         87        89        87
1       2  Vaidehi Laddha    9146         90        34        78
2       3    Sourabh Soni    9472         86        78        43
3       4     Eroze Barua    9528         43       NAN        90
4       5  Kanhaiya Sethi    9966         94        78       NAN

In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

In [ ]:
import pandas as pd

# Load an Excel file into a DataFrame
df_exe = pd.read_excel(r'/content/data_exp4.csv.xlsx', engine='openpyxl')
print(df_exe.head())

   S. NO             Name  SAP ID  Subject 1  Subject 2  Subject 3
0       1      Gazal Garg    9972         87         89         87
1       2  Vaidehi Laddha    9146         90         34         78
2       3    Sourabh Soni    9472         86         78         43
3       4     Eroze Barua    9528         43         23         90
4       5  Kanhaiya Sethi    9966         94         78         32

In [ ]:
print(df_csv.shape)

(5, 6)

In [ ]:
print(df_csv.columns)

Index(['S. NO ', 'Name', 'SAP ID', 'Subject 1', 'Subject 2', 'Subject 3'], dtype='object')

In [ ]:
# Display the first 5 rows
print(df_csv.head(2))

# Display the last 5 rows
print(df_csv.tail(2))

   S. NO             Name  SAP ID  Subject 1 Subject 2 Subject 3
0       1      Gazal Garg    9972         87        89        87
1       2  Vaidehi Laddha    9146         90        34        78
   S. NO             Name  SAP ID  Subject 1 Subject 2 Subject 3
3       4     Eroze Barua    9528         43       NAN        90
4       5  Kanhaiya Sethi    9966         94        78       NAN

In [ ]:
print(df_csv.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   S. NO      5 non-null      int64
 1   Name       5 non-null      object
 2   SAP ID     5 non-null      int64
 3   Subject 1  5 non-null      int64
 4   Subject 2  5 non-null      object
 5   Subject 3  5 non-null      object
dtypes: int64(3), object(3)
memory usage: 368.0+ bytes
None

In [ ]:
print(df_csv.describe())

         S. NO        SAP ID  Subject 1
count  5.000000     5.000000   5.000000
mean   3.000000  9616.800000  80.000000
std    1.581139   353.062601  20.916501
min    1.000000  9146.000000  43.000000
25%    2.000000  9472.000000  86.000000
50%    3.000000  9528.000000  87.000000
75%    4.000000  9966.000000  90.000000
max    5.000000  9972.000000  94.000000

In [ ]:
column_a = df_csv['Subject 2']
selected_columns = df_csv[['Subject 2', 'Subject 1']]
column_a

0     89
1     34
2     78
3    NAN
4     78
Name: Subject 2, dtype: object

In [ ]:
selected_columns

  Subject 2  Subject 1
0        89         87
1        34         90
2        78         86
3       NAN         43
4        78         94

In [ ]:
first_three_rows = df_csv[:3]
row_by_label = df_csv.iloc[3]
subset = df_csv.iloc[5:10, [0, 2]]

In [ ]:
first_three_rows

   S. NO             Name  SAP ID  Subject 1  Subject 2  Subject 3
0       1      Gazal Garg    9972         87         89         87
1       2  Vaidehi Laddha    9146         90         34         78
2       3    Sourabh Soni    9472         86         78         43

In [ ]:
row_by_label

S. NO                  4
Name         Eroze Barua
SAP ID              9528
Subject 1             43
Subject 2            NAN
Subject 3             90
Name: 3, dtype: object

In [ ]:
subset

Empty DataFrame
Columns: [S. NO , SAP ID]
Index: []

In [ ]:
# Sample DataFrame with missing values
data = {'A': [1, 2, None, 4], 'B': [5, None, None, 8], 'C': [9, 10, 11, None]}
df = pd.DataFrame(data)

# Identify missing values using isnull() or isna()
missing_values = df.isnull()  # or df.isna()
print(missing_values)

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False
3  False  False   True

In [ ]:
# Fill missing values with a specific value (e.g., 0)
df_filled = df.fillna(0)

# Drop rows with missing values
df_dropped = df.dropna()

# Interpolate missing values (useful for numerical data)
df_interpolated = df.interpolate()

print(df_filled)
print(df_dropped)
print(df_interpolated)

     A    B     C
0  1.0  5.0   9.0
1  2.0  0.0  10.0
2  0.0  0.0  11.0
3  4.0  8.0   0.0
     A    B    C
0  1.0  5.0  9.0
     A    B     C
0  1.0  5.0   9.0
1  2.0  6.0  10.0
2  3.0  7.0  11.0
3  4.0  8.0  11.0

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Sample numerical data
numerical_data = df[['A', 'B']].fillna(0)

# Min-Max Scaling
scaler = MinMaxScaler()
df_min_max_scaled = pd.DataFrame(scaler.fit_transform(numerical_data), columns=['A', 'B'])

# Z-Score Standardization
scaler = StandardScaler()
df_z_score_scaled = pd.DataFrame(scaler.fit_transform(numerical_data), columns=['A', 'B'])

print(df_min_max_scaled)
print(df_z_score_scaled)

      A      B
0  0.25  0.625
1  0.50  0.000
2  0.00  0.000
3  1.00  1.000
          A         B
0 -0.507093  0.511891
1  0.169031 -0.950654
2 -1.183216 -0.950654
3  1.521278  1.389418

In [ ]:
# Sample categorical data
df_cat = pd.DataFrame({'Category': ['A', 'B', 'A', 'C']})

# Create dummy variables
df_dummies = pd.get_dummies(df_cat, prefix='Category')

print(df_dummies)

   Category_A  Category_B  Category_C
0        True       False       False
1       False        True       False
2        True       False       False
3       False       False        True

Aggregation and Grouping

In [ ]:
# Sample DataFrame
data = {'Category': ['A', 'B', 'A', 'B', 'A'],
        'Value': [10, 15, 10, 20, 10]}
df = pd.DataFrame(data)

# Group by 'Category' and calculate summary statistics
grouped = df.groupby('Category').agg(['mean', 'median', 'count'])

print(grouped)

         Value
          mean median count
Category
A         10.0   10.0     3
B         17.5   17.5     2

In [ ]:
# Sample DataFrame
data = {'Category': ['A', 'A', 'B', 'B'],
        'SubCategory': ['X', 'Y', 'X', 'Y'],
        'Value': [10, 20, 30, 40]}
df = pd.DataFrame(data)

# Create pivot table
pivot_table = df.pivot_table(values='Value', index='Category', columns='SubCategory', aggfunc='mean')

print(pivot_table)

SubCategory     X     Y
Category
A            10.0  20.0
B            30.0  40.0

In [ ]:
# Sample DataFrames
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'], 'B': ['B0', 'B1', 'B2']})
df2 = pd.DataFrame({'A': ['A0', 'A1', 'A3'], 'C': ['C0', 'C1', 'C3']})

# Concatenation
df_concat = pd.concat([df1, df2], axis=0)  # Vertical (default)
df_concat_hor = pd.concat([df1, df2], axis=1)  # Horizontal

# Merge (Inner join by default)
df_merged = pd.merge(df1, df2, on='A')

# Join (uses the index by default)
df_joined = df1.join(df2.set_index('A'), on='A')

print(df_concat)
print(df_merged)
print(df_joined)

    A    B    C
0  A0   B0  NaN
1  A1   B1  NaN
2  A2   B2  NaN
0  A0  NaN   C0
1  A1  NaN   C1
2  A3  NaN   C3
    A   B   C
0  A0  B0  C0
1  A1  B1  C1
    A   B    C
0  A0  B0   C0
1  A1  B1   C1
2  A2  B2  NaN

In [ ]:
# Inner Join (default in merge)
df_inner = pd.merge(df1, df2, on='A', how='inner')

# Outer Join
df_outer = pd.merge(df1, df2, on='A', how='outer')

# Left Join
df_left = pd.merge(df1, df2, on='A', how='left')

# Right Join
df_right = pd.merge(df1, df2, on='A', how='right')

print(df_inner)
print(df_outer)
print(df_left)
print(df_right)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
    A    B    C
0  A0   B0   C0
1  A1   B1   C1
2  A2   B2  NaN
3  A3  NaN   C3
    A   B    C
0  A0  B0   C0
1  A1  B1   C1
2  A2  B2  NaN
    A    B   C
0  A0   B0  C0
1  A1   B1  C1
2  A3  NaN  C3